#!/usr/bin/env bash

# Function to display information about a subdomain
display_info() {
    local subdomain=$1
    local domain=$2

    # Retrieve DNS information using dig command
    dns_info=$(dig +short $subdomain.$domain)

    # Check if the DNS information is not empty
    if [ -n "$dns_info" ]; then
        # Display the information with the record type 'A'
        echo "The subdomain $subdomain is a A record and points to $dns_info"
    else
        # Display a message if DNS information is not available
        echo "No DNS information available for the subdomain $subdomain"
    fi
}

# Main script

# Check if both domain and subdomain are provided as arguments
if [ "$#" -eq 2 ]; then
    display_info $2 $1

# If only domain is provided, display information for specific subdomains
elif [ "$#" -eq 1 ]; then
    domain=$1
    subdomains=("www" "lb-01" "web-01" "web-02")

    # Loop through the subdomains and display information
    for subdomain in "${subdomains[@]}"; do
        display_info $subdomain $domain
    done

# Display usage instructions if incorrect number of arguments are provided
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
