#!/bin/bash
result=$(echo "ibase=water; $WATER + ibase=stir; $STIR" | bc -l | sed 's/^\./0./')
result_bestchol=$(echo "obase=bestchol; $result" | bc -l | sed 's/^\./0./')
echo "The sum of WATER and STIR is: $result_bestchol"
