#!/usr/bin/env bash
# Commands to install Nginx on Web-Sever-01

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

# Testing Nginx configurations for Syntax errors
sudo nginx -t

sudo service nginx reload
