#!/usr/bin/env bash
# Commands to install Nginx on Web-Sever-01

# Update the package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Print a message to the index file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Testing Nginx configurations for syntax errors
sudo nginx -t

# Reload Nginx to apply changes
sudo systemctl reload nginx
